const functions = require('firebase-functions');

const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);
//update for expo
exports.tripRequest = functions.https.onRequest((req, res) => {
  // Notification details.
  var handle_of_invitor = req.query.invitor.toString(); // handle
  var handle_of_invited = req.query.invited.toString();  //handle
  var trip_id = req.query.trip.toString(); //uid of trip
  console.log('processing trip request from ' + handle_of_invitor + ' to ' + handle_of_invited);
  // logic to get token, ids of invitor and invited
  //users / handles/ handle -> id

  admin.database().ref('/users/handles/').once('value').then(function(snapshot) {
          var invited_id = snapshot.child(handle_of_invited).val();

          admin.database().ref('/users/main/' + invited_id).once('value').then(function(snapshot) {
                  var key = snapshot.key;
                  console.log('device keys');
                  console.log(snapshot.child('instance_id').val());
                  var tokens = snapshot.child('instance_id').val();
                  for(var token_key in tokens){
                      var token = tokens[token_key];
                      // creating message to send
                      var body_msg = handle_of_invitor + " has invited you to join a trip!";
                      var payload = {
                          notification: {
                              title: "Trip Invitation",
                              body: body_msg
                          },
                          data: {
                              trip: trip_id,
                              invitor_id: handle_of_invitor,
                              invited_id: handle_of_invited
                          }
                      };
                      // update this return for http call maybe?
                      return admin.messaging().sendToDevice(token, payload).then((response) => {
                              if (response.successCount >=0 ) {
                                  res.status(200).end();
                              } else {
                                  // Everything is bad
                                  res.status(400).send('Issue with sending push notification');

                              }
                          });
                  }
              });
      });
    });
//to add a push token to a user account
exports.addPushToken = functions.https.onRequest((req, res) => {
  var handle  = req.query.handle.toString(); //handle of user
  var token = req.query.token.toString(); //new token of user
  console.log('adding token ' + token + ' to user ' + handle);
  //go through process to add token
  admin.database().ref('/users/handles/').once('value').then(function(snapshot) {
          var handle_id = snapshot.child(handle).val();
          var postsRef = admin.database().ref('/users/main/' + handle_id + '/instance_ids/');
          var newPostRef = postsRef.push(token);
          // Get the unique key generated by push()
          //var postId = newPostRef.key;
          //postsRef.push().set({
          //  postId: token
          //});

});
if (req === undefined) {
    // This is an error case, as "message" is required
    res.status(400).send('No message defined!');
  } else {
    // Everything is ok
    console.log(req.body.message);
    res.status(200).end();
  }
});
